// AUTO-GENERATED by tools/gen_fragments_cpp.py -- DO NOT EDIT.
// Source of truth: oracle_generator/fragments.py
#ifndef ORACLE_FRAGMENTS_H
#define ORACLE_FRAGMENTS_H

namespace oracle {

struct Fragment { const char* text; int tone; };

static const Fragment kMoon_0[] = {
    {"The sky holds no moon tonight, {name} -- a good night to plant an idea rather than defend one.", 1},
    {"New moon. Nothing is owed yet. Begin quietly.", 0},
    {"Everything starts unlit. Let this beginning stay small enough to keep.", 3},
    {"A dark sky is not an empty one; it is a page before the first word.", 3},
    {"Tonight the moon steps back so you can hear your own intention, {name}.", 1},
    {"Plant the seed, then cover it. Not everything worthwhile needs an audience yet.", 0},
    {"The new moon asks a soft question: what would you begin if no one were watching?", 3},
    {"Beginnings rarely announce themselves. This one is content to be quiet.", 0},
    {"Under a moonless sky, small resolves count as much as grand ones.", 1},
    {"Nothing has to be finished today. It only has to be started.", 1},
    {"The lamp is unlit, {name}, but your hand still knows where the wick is.", 0},
    {"A fresh cycle opens. Spend it on one thing you actually want.", 1},
    {"Darkness at the start is ordinary, not ominous. Keep walking.", 0},
    {"First days are for intentions, not results. Set one and let it rest.", 3},
    {"The moon is gathering itself again. So, quietly, are you.", 0},
    {"An empty sky is generous: it gives you room to imagine before you commit.", 3},
};
static const int kMoon_0_count = 16;

static const Fragment kMoon_1[] = {
    {"A thin blade of light returns. Small progress is still progress, {name}.", 1},
    {"The crescent leans forward like something learning to grow.", 3},
    {"A little light is back in the sky. Add a little of your own.", 1},
    {"The moon is barely a sliver, yet it is unmistakably on its way.", 0},
    {"Momentum starts as a whisper. Listen for yours today.", 1},
    {"What you tended in the dark is beginning to show. Keep tending it.", 0},
    {"A crescent moon is proof that returning counts as arriving.", 3},
    {"Growth this early is fragile and real at once. Protect it, {name}.", 0},
    {"The sky is filling in slowly. There is no rush written anywhere in it.", 0},
    {"One more line of light than yesterday. That is the whole task.", 1},
    {"Early effort feels like almost nothing. It is not nothing.", 1},
    {"The crescent is a promise the moon keeps every month. Keep yours.", 3},
    {"Build on the small thing that worked. Ignore, for now, the large thing that didn't.", 1},
    {"A young moon doesn't apologise for being incomplete. Neither should you.", 0},
    {"The light is thin but climbing. Let today be a step, not a summit.", 0},
};
static const int kMoon_1_count = 15;

static const Fragment kMoon_2[] = {
    {"Half-lit and climbing: the moon is at the point where effort meets resistance, {name}.", 1},
    {"First quarter. Half in shadow, half in light -- an honest picture of most decisions.", 3},
    {"The moon has reached its first crossroads. So, perhaps, have you.", 3},
    {"This is the phase of push. If something needs your weight against it, lean now.", 1},
    {"Half the sky is lit. That is enough to see the next step by.", 0},
    {"Tension between what you started and what it's asking of you is normal here.", 0},
    {"The moon does not pause at the halfway line, and neither must you, {name}.", 1},
    {"A quarter moon is a decision made visible: commit, or gently let go.", 3},
    {"Resistance now is a sign you've reached the part that matters.", 1},
    {"Halfway is not stuck. Halfway is moving.", 0},
    {"The bright half and the dark half share the same moon. Let them share you too.", 3},
    {"Push where it gives. Rest where it doesn't. The moon does both in turn.", 0},
    {"First-quarter light is the light of doing, not dreaming. Do a little.", 1},
    {"You are far enough in to feel the friction. That is the good news.", 1},
    {"Choose the harder half today, {name}, and the moon will meet you there.", 1},
};
static const int kMoon_2_count = 15;

static const Fragment kMoon_3[] = {
    {"Almost full. The moon is nearly there, and so, more than you think, are you, {name}.", 1},
    {"Waxing gibbous: the phase of refinement, not invention. Polish what you have.", 3},
    {"The moon is fattening toward fullness. Trust the work you've already done.", 0},
    {"Nearly complete is a fine place to be. Resist the urge to start over.", 0},
    {"The last stretch before full is where patience earns its keep.", 1},
    {"Most of the sky is bright now. Attend to the small, dim corners that remain.", 3},
    {"You are closer than the doubt in your head suggests, {name}.", 0},
    {"Gibbous light is generous. Let some of it fall on what you've made.", 4},
    {"Refinement is quieter than creation and just as important.", 3},
    {"The moon rounds itself out slowly. Give your own edges the same grace.", 0},
    {"Nearly full means nearly ready. Steady hands from here.", 1},
    {"Don't confuse 'not finished' with 'not working.' It is working.", 0},
    {"The final degrees of a climb feel the steepest. Keep the pace kind.", 1},
    {"Almost-round, almost-there: the moon models the last mile beautifully.", 3},
    {"Tend the details now, {name}; the shape is already good.", 1},
};
static const int kMoon_3_count = 15;

static const Fragment kMoon_4[] = {
    {"The moon is full and unhidden tonight, {name}. Let something be seen that you usually keep quiet.", 4},
    {"Full moon. Whatever you've been building is standing in plain light now.", 4},
    {"Fullness is not the end of a thing, only its most visible moment.", 3},
    {"The whole disc is lit. Pause long enough to notice how far the cycle has come.", 3},
    {"Tonight the sky is at its brightest. Let yourself be, briefly, satisfied.", 4},
    {"A full moon reveals; it does not judge. Look kindly at what it shows you.", 0},
    {"Everything is illuminated tonight, {name} -- the good work and the loose ends alike.", 3},
    {"Completion has its own light. Stand in it for a moment before the next thing.", 4},
    {"The moon holds nothing back tonight. Consider what you might stop hiding.", 1},
    {"Full light can feel like exposure. It is also, quietly, an invitation to be honest.", 3},
    {"This is the summit of the cycle. Enjoy the view; the descent is gentle.", 4},
    {"What ripened this month is ripe now. Harvest a little of it, {name}.", 4},
    {"A full moon asks nothing new of you. It only asks you to notice.", 0},
    {"Brightness like this is temporary and worth marking. Mark it.", 4},
    {"The moon is whole tonight. Let one whole feeling have its turn.", 3},
};
static const int kMoon_4_count = 15;

static const Fragment kMoon_5[] = {
    {"The moon has begun to give its light back. So can you, {name} -- share what you learned.", 3},
    {"Waning gibbous: the phase of gratitude and telling. Speak what worked.", 1},
    {"Just past full, the sky starts to soften. Softening is not the same as losing.", 0},
    {"The moon is spending down its brightness. Spend some of yours on others.", 1},
    {"This is the season of afterthought and thank-you. Both are worth your time.", 3},
    {"Light is receding, gently. There is nothing to fix in that; it is the design.", 0},
    {"What you gathered at the full, {name}, is yours to pass along now.", 1},
    {"The disc is dimming a little each night. Let the day feel a little less urgent too.", 0},
    {"After the peak comes the sharing. Generosity suits this phase.", 1},
    {"The moon teaches how to let go without alarm. Take the lesson slowly.", 3},
    {"Reflection is the natural work of a waning sky. Do a little tonight.", 3},
    {"You don't have to hold the whole light. Set some of it down, {name}.", 0},
    {"The brightest part is behind you, and that is perfectly, usefully fine.", 0},
    {"Tell someone what the last cycle taught you. That is how light gets shared.", 1},
    {"A dimming moon is still a moon. You, dimming a little, are still you.", 0},
};
static const int kMoon_5_count = 15;

static const Fragment kMoon_6[] = {
    {"Half-dark and falling: the moon is clearing space now. Consider what to release, {name}.", 3},
    {"Last quarter. Half the light is already gone, and the sky is not distressed about it.", 0},
    {"This is the phase of letting go on purpose rather than by accident.", 3},
    {"The waning half-moon marks a turn inward. Follow it a little way.", 3},
    {"Clearing out is honest work. Do some of it while the moon models the way.", 1},
    {"Half is lit, half is done with being lit. Some things you can put down now.", 0},
    {"The moon is subtracting, calmly. Subtraction can be a kindness, {name}.", 0},
    {"What no longer fits can be set at the edge of the path and left there.", 1},
    {"A last-quarter sky asks a fair question: what has finished its work in you?", 3},
    {"Release is not defeat. The moon proves it every month without complaint.", 0},
    {"Make a little room. The next cycle will want it.", 1},
    {"The descending half-moon is a good hour for forgiveness -- including your own.", 0},
    {"Loosen your grip on one thing today, {name}. Just one is enough.", 1},
    {"Half-light is enough light to sort by. Keep what serves; release what strains.", 3},
    {"The sky is emptying toward rest. Let part of your day empty too.", 0},
};
static const int kMoon_6_count = 15;

static const Fragment kMoon_7[] = {
    {"Only a thin arc remains, {name}. The cycle is nearly closed; let yourself rest before the next.", 0},
    {"Waning crescent: the last light before the dark. A phase for rest, not resolve.", 0},
    {"The moon is a fading curve now, unhurried about its own ending.", 3},
    {"Almost gone is not the same as gone. There is still a little light to steer by.", 0},
    {"This is the sky's quiet exhale. Match it if you can.", 3},
    {"The old moon thins toward nothing so a new one can begin. Trust the turn.", 0},
    {"Little is left of this cycle's light, {name}, and that is exactly on schedule.", 0},
    {"Rest is not idleness here; it is preparation. Let it be enough.", 0},
    {"The final sliver asks nothing of you but stillness. Grant it.", 0},
    {"Endings, like this crescent, can be gentle. Let this one be.", 3},
    {"Close the cycle kindly. Loose ends can wait for the new moon.", 1},
    {"The last curve of light is a good place to be quiet and grateful.", 3},
    {"You have carried enough for one cycle. Set it down before dawn, {name}.", 0},
    {"A vanishing moon teaches that emptying makes room. Believe it a little.", 3},
    {"Soon the sky resets. Until then, be soft with yourself.", 0},
};
static const int kMoon_7_count = 15;

static const Fragment* const kMoonPools[] = {kMoon_0, kMoon_1, kMoon_2, kMoon_3, kMoon_4, kMoon_5, kMoon_6, kMoon_7};
static const int kMoonCounts[] = {kMoon_0_count, kMoon_1_count, kMoon_2_count, kMoon_3_count, kMoon_4_count, kMoon_5_count, kMoon_6_count, kMoon_7_count};

static const Fragment kPlanet_0[] = {
    {"Mercury moves backward through the sky today. Reread before you send, {name}.", 2},
    {"With Mercury retrograde, slow speech is wise speech. Say the second thing, not the first.", 2},
    {"Messages tangle more easily now. Ask 'did you mean...?' before you assume.", 2},
    {"Mercury retrograde is a fine excuse to finish an old draft rather than start a new one.", 1},
    {"Double-check the small print today; the sky is in a backtracking mood.", 2},
    {"When Mercury reverses, revisiting beats rushing. Return to something unfinished.", 3},
    {"A misheard word costs little if you're willing to ask again. Ask again, {name}.", 2},
    {"Mercury retrograde favours the patient editor over the quick sender.", 3},
    {"Travel and timing wobble a bit now. Leave a margin and let the day breathe.", 2},
    {"This is a good week to repair a conversation, not to force a new one.", 1},
    {"The sky suggests re-, not new-: review, repair, reconnect.", 3},
    {"If a plan feels slippery today, it may just be Mercury. Firm your grip gently.", 0},
};
static const int kPlanet_0_count = 12;

static const Fragment kPlanet_1[] = {
    {"Mercury runs forward and clear today. If there's a thing to say, {name}, say it plainly.", 1},
    {"The channels are open. Send the note you've been holding.", 1},
    {"A good day for straight talk and clean plans. Use the clarity.", 1},
    {"Mercury direct favours the messenger. Make the call you've been circling.", 1},
    {"Words land where you aim them today. Aim kindly.", 3},
    {"Thinking feels less tangled now. Untangle one thing while it's easy.", 1},
    {"The mind's roads are open, {name}. Take the direct route for once.", 1},
    {"Clarity is on offer today. Spend it on something that's been vague too long.", 1},
    {"A clear-signal day: write it down, say it out loud, make it real.", 1},
    {"Mercury moves ahead cleanly. So can the conversation you've postponed.", 1},
    {"Ideas travel well today. Let one leave your head and meet the world.", 1},
};
static const int kPlanet_1_count = 11;

static const Fragment kPlanet_2[] = {
    {"Venus turns back today, {name}. It's a season to revisit what you value, not to spend.", 3},
    {"With Venus retrograde, old feelings may resurface. Meet them with curiosity, not alarm.", 0},
    {"The sky asks you to review your affections rather than rearrange them. Look before you leap.", 2},
    {"Venus retrograde is kinder to reflection than to purchase. Pause the cart.", 2},
    {"Beauty turns inward now. Tend what you already love before seeking more.", 3},
    {"A returning Venus reopens old chapters. You may reread; you needn't rewrite.", 3},
    {"Value what's quietly loyal today over what's newly shiny, {name}.", 3},
    {"This is a week for gratitude toward what you have, not longing for what you don't.", 0},
    {"If an old fondness resurfaces, let it inform you before it moves you.", 2},
    {"Venus retrograde favours mending over acquiring. Mend a small thing.", 1},
    {"Hold big commitments loosely this week; the sky is still deciding with you.", 2},
};
static const int kPlanet_2_count = 11;

static const Fragment kPlanet_3[] = {
    {"Venus moves forward and warm today. Let a little beauty in on purpose, {name}.", 4},
    {"A generous sky for affection and craft. Make something, or tell someone.", 1},
    {"Venus direct favours the open hand. Offer, share, appreciate.", 4},
    {"Harmony is a little easier to reach today. Reach for it first.", 1},
    {"The day leans toward pleasure that's honest. Choose one small good thing.", 4},
    {"Venus runs clear now. Say the kind thing before the moment passes.", 1},
    {"Beauty is uncomplicated today, {name}. Notice some of it and let that be enough.", 3},
    {"A fine day to repair goodwill or simply enjoy it. Both count.", 1},
    {"Value moves outward now. Give a little of what you'd like to receive.", 1},
    {"Warmth travels well under a direct Venus. Send some.", 4},
    {"Let yourself like what you like today, without a defence prepared.", 0},
};
static const int kPlanet_3_count = 11;

static const Fragment kPlanet_4[] = {
    {"Mars turns backward today, {name}. Conserve your fire; not every provocation deserves it.", 2},
    {"With Mars retrograde, the wise move is often the unhurried one. Let the anger cool.", 2},
    {"Energy pulls inward now. Train, don't fight; plan, don't charge.", 1},
    {"A retrograde Mars rewards patience over force. Wait for the better angle.", 3},
    {"Push less today and aim more. The target isn't going anywhere.", 2},
    {"Frustration is loud under this sky. You don't have to answer it out loud, {name}.", 0},
    {"Mars retrograde is a good time to sharpen the tool, not swing it.", 3},
    {"Redirect the heat inward as resolve rather than outward as reaction.", 1},
    {"If a fight offers itself today, you're allowed to decline the invitation.", 2},
    {"Slow force is still force. Move deliberately and you lose nothing.", 0},
    {"The sky counsels restraint over conquest this week. Rest the sword arm.", 2},
};
static const int kPlanet_4_count = 11;

static const Fragment kPlanet_5[] = {
    {"Mars drives forward and clean today, {name}. If action's been waiting, this is its hour.", 1},
    {"The sky backs the doers now. Take the first concrete step.", 1},
    {"Mars direct favours momentum. Point your energy at one clear thing.", 1},
    {"Courage is a little cheaper today. Spend some on the task you've dodged.", 1},
    {"A day for honest effort. Begin, and let beginning be the win.", 1},
    {"Mars runs ahead cleanly. So can the project you've kept idling.", 1},
    {"Vigour is on offer, {name}. Aim it, don't just feel it.", 1},
    {"Directness suits the sky now. Do the plain, brave, boring next step.", 1},
    {"The path forward is unobstructed today. Walk a stretch of it.", 1},
    {"Strength is easiest to find in motion. Move first, feel ready after.", 1},
    {"Let today's energy build something rather than burn something.", 3},
};
static const int kPlanet_5_count = 11;

static const Fragment kPlanet_6[] = {
    {"Jupiter turns inward today, {name}. Growth this season is depth, not distance.", 3},
    {"With Jupiter retrograde, the expansion is internal. Grow roots before branches.", 3},
    {"The sky favours reviewing your beliefs over broadcasting them now.", 2},
    {"A retrograde Jupiter asks: is the goal still yours, or just old momentum?", 3},
    {"Luck turns philosophical this week. Learn from a delay instead of resenting it.", 0},
    {"Expand quietly, {name}. The best growth right now doesn't need a crowd.", 3},
    {"Jupiter retrograde rewards the honest audit over the bold gamble.", 2},
    {"Reconsider a big promise before you enlarge it. There's time.", 2},
    {"Wisdom compounds inwardly now. Sit with a question longer than usual.", 3},
    {"The sky counsels meaning over more. Ask what a thing is for.", 3},
    {"Optimism sharpens when it's examined. Examine yours kindly.", 3},
};
static const int kPlanet_6_count = 11;

static const Fragment kPlanet_7[] = {
    {"Jupiter moves forward and open today, {name}. Room is being made; step into a little of it.", 1},
    {"The sky favours growth now. Say yes to one thing slightly larger than yesterday.", 1},
    {"Jupiter direct widens the road. Take the more generous view.", 1},
    {"Opportunity travels well today. Keep your yes ready and your reasons kind.", 1},
    {"A day that rewards a bit of faith. Extend some to your own plans.", 0},
    {"Expansion is easier under a direct Jupiter. Reach one notch further.", 1},
    {"Good fortune likes motion, {name}. Meet it partway.", 1},
    {"The horizon looks a little closer today. Walk toward it without hurry.", 1},
    {"Generosity multiplies now. Be the one who offers first.", 4},
    {"Let the day's optimism be practical: one open door, one honest step.", 1},
    {"Growth is on offer. Choose the kind that also lets others grow.", 3},
};
static const int kPlanet_7_count = 11;

static const Fragment kPlanet_8[] = {
    {"Saturn turns back today, {name}. Revisit the structure before you build higher on it.", 3},
    {"With Saturn retrograde, the sky rewards repair of foundations over new floors.", 2},
    {"Discipline turns reflective now. Ask which rules still serve you.", 3},
    {"A retrograde Saturn is a chance to renegotiate a burden, not just carry it.", 0},
    {"Review your commitments this week. Some can be lightened without being broken.", 0},
    {"The sky favours consolidation over construction. Firm up what wobbles.", 2},
    {"Responsibility feels heavier under this sky, {name}. Set part of it down to rest.", 0},
    {"Saturn retrograde asks patience with slow things. Yours included.", 3},
    {"Rework the plan's frame before you decorate its rooms.", 2},
    {"Old duties resurface now. Honour the ones that still fit; retire the rest.", 3},
    {"Structure is worth revisiting, not worshipping. Adjust one beam.", 3},
};
static const int kPlanet_8_count = 11;

static const Fragment kPlanet_9[] = {
    {"Saturn moves forward and steady today, {name}. Lay one solid stone and trust it to hold.", 1},
    {"The sky rewards patient structure now. Do the unglamorous, lasting thing.", 1},
    {"Saturn direct favours the builder. Commit to a small, real discipline.", 1},
    {"Foundations set well today. Lay one and let it settle.", 1},
    {"A day for keeping a promise to yourself. Keep a plain one.", 0},
    {"Saturn steadies the ground now. Stand on it and plan the next course.", 1},
    {"Diligence pays quietly today, {name}. Choose the durable over the flashy.", 3},
    {"Structure is a kindness to your future self. Build a little of it now.", 3},
    {"The sky backs the reliable today. Be reliable to one thing that matters.", 1},
    {"Slow and solid wins under a direct Saturn. Set the pace and hold it.", 1},
    {"Order is on offer. Put one corner of your life gently in its place.", 1},
};
static const int kPlanet_9_count = 11;

static const Fragment* const kPlanetPools[] = {kPlanet_0, kPlanet_1, kPlanet_2, kPlanet_3, kPlanet_4, kPlanet_5, kPlanet_6, kPlanet_7, kPlanet_8, kPlanet_9};
static const int kPlanetCounts[] = {kPlanet_0_count, kPlanet_1_count, kPlanet_2_count, kPlanet_3_count, kPlanet_4_count, kPlanet_5_count, kPlanet_6_count, kPlanet_7_count, kPlanet_8_count, kPlanet_9_count};

static const Fragment kSeason_0[] = {
    {"No great turning in the sky today, {name} -- just an ordinary day, which is where most of a life is lived.", 0},
    {"The heavens are unremarkable today, and that is its own quiet gift.", 0},
    {"An ordinary day asks little and offers plenty if you let it.", 3},
    {"Nothing is peaking overhead. Good -- steadiness is underrated.", 0},
    {"Most days are plain days. Plain days are where the real work happens.", 3},
    {"The sky is calm today, {name}. Let that permission reach the rest of you.", 0},
    {"No cosmic drama tonight. Just you, the evening, and whatever you choose to make of it.", 3},
    {"An unhurried sky suits an unhurried heart. Take the day as it comes.", 0},
};
static const int kSeason_0_count = 8;

static const Fragment kSeason_1[] = {
    {"The sun stands still at its extreme today, {name} -- the year pauses, and you may too.", 3},
    {"Solstice. This is the hinge of the year; notice which way the light is about to turn.", 3},
    {"At the solstice the day is longest or shortest -- either way, a threshold worth marking.", 4},
    {"The sun reaches the edge of its road and turns back. Turnings deserve a breath.", 3},
    {"A solstice is the year holding its breath. Hold yours a moment with it.", 3},
    {"Extremes don't last; the solstice proves it. From here, balance returns slowly.", 0},
    {"Mark this turning, {name}. The light has reached its limit and begins its long answer.", 4},
    {"The solstice is a natural new leaf. Write one intention on it and close the book gently.", 1},
};
static const int kSeason_1_count = 8;

static const Fragment kSeason_2[] = {
    {"Day and night are equal today, {name}. Let something in your own life come level too.", 3},
    {"Equinox. Light and dark share the sky exactly; balance is briefly, beautifully literal.", 3},
    {"The equinox splits the day evenly. Consider where your own scales want adjusting.", 3},
    {"Perfect balance is rare and doesn't stay. The equinox offers a taste; take it.", 0},
    {"Equal parts light and dark, {name} -- a fair reminder that both belong to a full day.", 3},
    {"The equinox is the year's level ground. Stand on it and check your footing.", 3},
    {"Balance is a moment, not a destination. The sky demonstrates it today.", 3},
    {"At the equinox the world is even-handed. Try being even-handed with yourself.", 0},
};
static const int kSeason_2_count = 8;

static const Fragment* const kSeasonPools[] = {kSeason_0, kSeason_1, kSeason_2};
static const int kSeasonCounts[] = {kSeason_0_count, kSeason_1_count, kSeason_2_count};

static const Fragment kClosing[] = {
    {"Tomorrow's page is already turning. Sleep well, {name}.", 0},
    {"Whatever today held, the sky resets by morning. So can you.", 0},
    {"Take one small kindness into the evening -- ideally toward yourself.", 0},
    {"The stars keep their own schedule. You're allowed to keep yours.", 0},
    {"Rest is not a reward for finishing; it's part of the work. Take some.", 0},
    {"Let the day close without a verdict. Not everything needs judging tonight.", 3},
    {"Carry forward only what serves you. Leave the rest to the dark.", 1},
    {"The moon will be here tomorrow, and so, quietly, will you.", 0},
    {"Be gentle in the last hour of the day. It sets the tone for the next.", 0},
    {"One honest breath is a fine way to end an ordinary evening.", 3},
    {"You did enough today. Let that sentence be true.", 0},
    {"Close the day like a book you'll open again -- without tearing the page.", 3},
    {"The sky asks nothing more of you tonight. Neither should you, {name}.", 0},
    {"Small steps still count after dark. So does stopping.", 1},
    {"Let tomorrow be tomorrow's. Tonight is for setting things down.", 0},
    {"Somewhere overhead the pattern continues, steady and unbothered. Borrow its calm.", 3},
    {"Kindness scales. Offer a little to the person you'll be in the morning.", 1},
    {"The best plans can wait until you've slept. Sleep first.", 0},
    {"Mark one good thing from today before you forget it happened.", 4},
    {"The day is done and that is not a failure -- it's the design. Rest, {name}.", 0},
    {"Let the last thought of the day be a soft one.", 0},
    {"Tomorrow keeps its own light. Trust it to arrive.", 0},
};
static const int kClosing_count = 22;

}  // namespace oracle

#endif  // ORACLE_FRAGMENTS_H
