#!/usr/bin/env python3
"""Embed the ASCII-subset EB Garamond faces into firmware/src/oracle_font_ttf.h.

Source fonts (SIL OFL 1.1) live in firmware/fonts/. This regenerates the C
byte-array header consumed by the stb_truetype renderer so the same serif is
used on desktop and on the ESP32.

Run:  python3 tools/gen_font_cpp.py
"""

from __future__ import annotations

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONTS = os.path.join(ROOT, "firmware", "fonts")
OUT = os.path.join(ROOT, "firmware", "src", "oracle_font_ttf.h")

FACES = [
    ("EBGaramond-Regular-ascii.ttf", "kEBGaramondRegular"),
    ("EBGaramond-SemiBold-ascii.ttf", "kEBGaramondSemiBold"),
]


def emit(path: str, arrname: str, out: list[str]) -> int:
    with open(path, "rb") as f:
        data = f.read()
    out.append(f"static const unsigned char {arrname}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("  " + ",".join(str(b) for b in chunk) + ",")
    out.append("};")
    out.append(f"static const unsigned int {arrname}_len = {len(data)};")
    out.append("")
    return len(data)


def main() -> int:
    out = [
        "// AUTO-GENERATED by tools/gen_font_cpp.py -- DO NOT EDIT.",
        "// EB Garamond (SIL OFL 1.1), ASCII-subset. See firmware/fonts/EBGaramond-OFL.txt",
        "#ifndef ORACLE_FONT_TTF_H",
        "#define ORACLE_FONT_TTF_H",
        "",
        "namespace oracle {",
        "",
    ]
    sizes = []
    for fname, arr in FACES:
        sizes.append(emit(os.path.join(FONTS, fname), arr, out))
    out += ["}  // namespace oracle", "", "#endif  // ORACLE_FONT_TTF_H"]
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"Wrote {OUT}: regular={sizes[0]}B semibold={sizes[1]}B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
