#!/usr/bin/env python3
"""Generate firmware/src/oracle_fragments.h from the Python fragment bank.

The Python module oracle_generator/fragments.py is the single source of truth.
This keeps the C++ (ESP32) copy byte-identical so both platforms produce the
same messages from the same seed.

Run:  python3 tools/gen_fragments_cpp.py
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from oracle_generator import fragments  # noqa: E402

OUT = os.path.join(ROOT, "firmware", "src", "oracle_fragments.h")

# Fixed orders that must match the C++ enums / key indexing.
MOON_ORDER = [
    "new", "waxing_crescent", "first_quarter", "waxing_gibbous",
    "full", "waning_gibbous", "last_quarter", "waning_crescent",
]
# planet key index = planet*2 + (retro?0:1)
PLANET_ORDER = [
    "mercury_retrograde", "mercury_direct",
    "venus_retrograde", "venus_direct",
    "mars_retrograde", "mars_direct",
    "jupiter_retrograde", "jupiter_direct",
    "saturn_retrograde", "saturn_direct",
]
SEASON_ORDER = ["ordinary", "solstice", "equinox"]  # kind index 0,1,2

# Tone enum order must match composer/header.
TONES = ["reassuring", "encouraging", "cautionary_gentle", "reflective", "celebratory"]


def c_escape(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    # Replace the literary en/em dashes with ASCII so the bitmap font can draw
    # them; the C++ renderer maps " -- " visually. Keep {name} token intact.
    return out


def emit_list(lines_out, name, items):
    """items: list of (text, tone). Emit a C array of Fragment structs."""
    lines_out.append(f"static const Fragment {name}[] = {{")
    for text, tone in items:
        t = TONES.index(tone)
        lines_out.append(f'    {{"{c_escape(text)}", {t}}},')
    lines_out.append("};")
    lines_out.append(f"static const int {name}_count = {len(items)};")
    lines_out.append("")


def main() -> int:
    out = []
    out.append("// AUTO-GENERATED by tools/gen_fragments_cpp.py -- DO NOT EDIT.")
    out.append("// Source of truth: oracle_generator/fragments.py")
    out.append("#ifndef ORACLE_FRAGMENTS_H")
    out.append("#define ORACLE_FRAGMENTS_H")
    out.append("")
    out.append("namespace oracle {")
    out.append("")
    out.append("struct Fragment { const char* text; int tone; };")
    out.append("")

    # Moon phases.
    for i, key in enumerate(MOON_ORDER):
        emit_list(out, f"kMoon_{i}", fragments.MOON_PHASE[key])
    out.append("static const Fragment* const kMoonPools[] = {"
               + ", ".join(f"kMoon_{i}" for i in range(len(MOON_ORDER))) + "};")
    out.append("static const int kMoonCounts[] = {"
               + ", ".join(f"kMoon_{i}_count" for i in range(len(MOON_ORDER))) + "};")
    out.append("")

    # Planetary states.
    for i, key in enumerate(PLANET_ORDER):
        emit_list(out, f"kPlanet_{i}", fragments.PLANETARY_EMPHASIS[key])
    out.append("static const Fragment* const kPlanetPools[] = {"
               + ", ".join(f"kPlanet_{i}" for i in range(len(PLANET_ORDER))) + "};")
    out.append("static const int kPlanetCounts[] = {"
               + ", ".join(f"kPlanet_{i}_count" for i in range(len(PLANET_ORDER))) + "};")
    out.append("")

    # Season markers.
    for i, key in enumerate(SEASON_ORDER):
        emit_list(out, f"kSeason_{i}", fragments.SEASON_MARKER[key])
    out.append("static const Fragment* const kSeasonPools[] = {"
               + ", ".join(f"kSeason_{i}" for i in range(len(SEASON_ORDER))) + "};")
    out.append("static const int kSeasonCounts[] = {"
               + ", ".join(f"kSeason_{i}_count" for i in range(len(SEASON_ORDER))) + "};")
    out.append("")

    # Closings.
    emit_list(out, "kClosing", fragments.CLOSING_LINES)

    out.append("}  // namespace oracle")
    out.append("")
    out.append("#endif  // ORACLE_FRAGMENTS_H")

    total = (sum(len(fragments.MOON_PHASE[k]) for k in MOON_ORDER)
             + sum(len(fragments.PLANETARY_EMPHASIS[k]) for k in PLANET_ORDER)
             + sum(len(fragments.SEASON_MARKER[k]) for k in SEASON_ORDER)
             + len(fragments.CLOSING_LINES))

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"Wrote {OUT} ({total} fragments)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
